### ISSUE TITLE
Increments all tasks/doesn't reset

### ISSUE THREAD

**Issue by notbored** [amitness/habitist#19] opened 2020-10-29 17:25 UTC
Recently habitist is just incrementing everything regardless if it's a new task/overdue/rescheduled. 

I've not changed anything code wise and I've created new tasks to test whether it was something going on with existing Todoist tasks but it increments everything regardless if it's been completed/overdue or new/existing. Also noticed that it is resetting completed tasks to 0, it does this but then increments uncompleted tasks at the same time.

**Comment by amitness** [comment] 2020-11-04 06:28
@notbored That's interesting. I noticed habit tasks being deleted randomly but couldn't figure out the root cause yet.

**Comment by notbored** [comment] 2020-11-04 12:05
I'm thinking something's changed on Todist's end.

To test again I deleted all my tasks and created new ones. I only completed one and left the rest to go overdue and everything that was overdue was incremented by 1 and and the completed one stayed at 0.

Think for the time being I'm just going to have to use another habit tracker or create my own.(the world always needs more to-do apps! XD)

**Comment by amitness** [comment] 2020-11-21 04:33
@notbored I have pushed a fix and it seems to work on my end. If you're still using habist, please sync the latest changes from the repo.

**Closed by amitness** 2020-11-21 04:33 UTC
